---
kind: pipeline
name: default

trigger:
  branch:
  - master

steps:
- name: clone-submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update

- name: install
  image: node
  volumes:
  - name: hugo-bin
    path: /usr/local/bin
  commands:
  - npx pnpm i
  - npx pnpm run install-theme
  - cp /drone/src/theme/scarecrow/node_modules/fuse.js/dist/fuse.js /drone/src/theme/scarecrow/assets/scripts/fuse.min.js
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.62.0/hugo_extended_0.62.0_Linux-64bit.deb
  - dpkg -i hugo.deb

- name: build
  image: node
  volumes:
  - name: hugo-bin
    path: /usr/local/bin
  commands:
  - hugo

volumes:
- name: hugo-bin
  temp: {}




# language: node_js
# node_js: lts/*

# cache:
#   npm: true
#   directories:
#   - $HOME/.pnpm-store/

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - libcairo2-dev
#       - libjpeg8-dev
#       - libpango1.0-dev
#       - libgif-dev
#       - librsvg2-dev
#       - g++-4.9

# env:
#   - CXX=g++-4.9

# before_install:
# - curl -L https://unpkg.com/@pnpm/self-installer | node
# # This workaround is required to avoid libstdc++ errors while running "extended" hugo with SASS support.
# # See: https://discourse.gohugo.io/t/solved-hugo-v44-extended-and-relocation-errors-on-travis/13029/5
# - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.12_amd64.deb
# - sudo dpkg --force-all -i libstdc++6
# install:
# - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.62.1/hugo_extended_0.62.1_Linux-64bit.deb
# - sudo dpkg -i hugo.deb
# - npm install

# script:
# - pnpm run build

# deploy:
#   provider: pages
#   repo: strootje/strootje.github.io
#   target-branch: master
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   skip-cleanup: true
#   local-dir: ./public
#   on:
#     branch: master
